# Generated by Django 5.0.6 on 2025-07-16 02:14

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Name')),
                ('descripcion', models.TextField(verbose_name='Desc')),
                ('duracion', models.IntegerField(verbose_name='plazo')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='cost')),
                ('activo', models.BooleanField(default=True, verbose_name='state')),
                ('imagen', models.ImageField(null=True, upload_to='fotos', verbose_name='img')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Creacion')),
                ('desc', ckeditor.fields.RichTextField(verbose_name='Descripcion')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-created'],
            },
        ),
    ]
