# Generated by Django 5.0.6 on 2025-06-30 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='duracion_horas',
            new_name='duracion',
        ),
    ]
