# Generated by Django 5.0.6 on 2025-07-16 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_actividad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actividad',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
